default:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

docker-build-main:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend" --target backend .
    - docker push "$CI_REGISTRY_IMAGE/backend"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/worker" --target worker .
    - docker push "$CI_REGISTRY_IMAGE/worker"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/frontend" --target frontend .
    - docker push "$CI_REGISTRY_IMAGE/frontend"
  only:
    - main

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" --target backend .
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/worker:$CI_COMMIT_REF_SLUG" --target worker .
    - docker push "$CI_REGISTRY_IMAGE/worker:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG" --target frontend .
    - docker push "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG"
  except:
    - main
