include:
  - project: tools/ci
    file: buildkit.yml
  - project: tools/ci
    file: python-poetry.yml

.ssh-agent:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - \[ -z "$SSH_PRIVATE_KEY" ] || (echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -)
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod -R go= ~/.ssh

stages:
  - test
  - publish
  - deploy

test cpython:
  extends: .pytest-cov
  before_script:
    - !reference [.python-setup, before_script]
    - apt-get update && apt-get install -y libpq-dev redis-server
    - poetry install --no-root -E worker -E test


publish docker:
  needs:
    - job: test cpython
  variables:
    IMAGE_SUFFIX: "/backend"
    BUILDKIT_OPT_ARGS: --opt target=backend

publish docker worker:
  extends: publish docker
  variables:
    IMAGE_SUFFIX: "/worker"
    BUILDKIT_OPT_ARGS: --opt target=worker

publish docker frontend:
  extends: publish docker
  variables:
    IMAGE_SUFFIX: "/frontend"
    BUILDKIT_OPT_ARGS: --opt target=frontend

deploy dev:
  needs:
    - job: publish docker
    - job: publish docker worker
    - job: publish docker frontend
  environment: dev
  stage: deploy
  image: cytopia/ansible:latest-tools
  tags:
    - docker
  before_script:
    - !reference [.ssh-agent, before_script]
  script:
    - cd deployment && ansible-playbook -i "${DEPLOY_HOST}," deploy.yml
  only:
    - dev
