default:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - \[ -z "$SSH_PRIVATE_KEY" ] || (echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  image: docker:latest
  services:
    - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

stages:
  - build
  - push
  - deploy

build main backend:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend" --target backend .
  only:
    - main

build main worker:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/worker" --target worker .
  only:
    - main

build main frontend:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/frontend" --target frontend .
  only:
    - main

push main backend:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE/backend"
  only:
    - main

push main worker:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE/worker"
  only:
    - main

push main frontend:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE/frontend"
  only:
    - main

deploy main:
  environment: production
  stage: deploy
  script:
    - ssh-add -L
  only:
    - main

build other all:
  # Official docker image.
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" --target backend .
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/worker:$CI_COMMIT_REF_SLUG" --target worker .
    - docker push "$CI_REGISTRY_IMAGE/worker:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG" --target frontend .
    - docker push "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG"
  except:
    - main
