default:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build-main:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend" .
    - docker push "$CI_REGISTRY_IMAGE/backend"
  only:
    - main

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
  except:
    - main
