version: '3'
services:

  postgres:
    image: "postgres:13"
    ports:
      - "127.0.0.1:2999:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
