version: '3.4'

services:
  db:
    networks:
      - db
      - default

  backend:
    image: ${IMAGE_BASE}/backend-dev:dev
    build:
      context: .
      target: backend-builder
      dockerfile: Dockerfile
    read_only: false
    environment:
      SANIC_DEBUG: "true"
      SANIC_DB_HOST: db
      SANIC_DB_USER: sanic
      SANIC_DB_PASSWORD: toomanysecrets
      SANIC_DB_NAME: sanic
      SANIC_ACCESS_LOG: "true"
      SANIC_WORKERS: 1
      SANIC_BIND_HOST: 0.0.0.0
      SANIC_BIND_PORT: 8000
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    volumes:
      - .:/app
      - backend_venv:/app/.venv
      - poetry_backend_cache:/root/.cache
    networks:
      - db
      - web
      - redis
      - default
    command:
      "sh -c 'poetry install && poetry run python -m unchanging_ink'"

  worker:
    image: ${IMAGE_BASE}/worker-dev:dev
    build:
      context: .
      target: worker-builder
      dockerfile: Dockerfile
    read_only: false
    environment:
      SANIC_DEBUG: "true"
      SANIC_DB_HOST: db
      SANIC_DB_USER: sanic
      SANIC_DB_PASSWORD: toomanysecrets
      SANIC_DB_NAME: sanic
      SANIC_ACCESS_LOG: "true"
      SANIC_WORKERS: 1
      SANIC_BIND_HOST: 0.0.0.0
      SANIC_BIND_PORT: 8000
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    volumes:
      - .:/app
      - worker_venv:/app/.venv
      - poetry_worker_cache:/root/.cache
    networks:
      - db
      - redis
      - default
    command:
      "sh -c 'poetry install -E worker && poetry run python -m unchanging_ink.worker'"

  frontend:
    image: ${IMAGE_BASE}/frontend-dev:dev
    build:
      context: .
      target: frontend-base
      dockerfile: Dockerfile.dev
    read_only: false
    volumes:
      - ./web/unchanging-ink:/app
      - ./doc:/app/content/doc
    environment:
      DISABLE_OPENCOLLECTIVE: true
    networks:
      - web
      - redis
      - default
    command: "sh -c 'cd /app && npm install && npm run dev'"
    tmpfs:
      - /root/.npm
      - /app/.nuxt
      - /app/node_modules:exec

volumes:
  backend_venv:
    driver_opts:
      type: tmpfs
      device: tmpfs
  worker_venv:
    driver_opts:
      type: tmpfs
      device: tmpfs
  poetry_backend_cache:
  poetry_worker_cache:
