version: '3'

services:
  backend:
    image: unchanging-ink:dev
    build:
      context: .
      target: builder-base
      dockerfile: Dockerfile
    read_only: false
    environment:
      SANIC_DEBUG: "true"
      SANIC_DB_HOST: db
      SANIC_DB_USER: sanic
      SANIC_DB_PASSWORD: toomanysecrets
      SANIC_DB_NAME: sanic
      SANIC_ACCESS_LOG: "true"
      SANIC_WORKERS: 1
      SANIC_BIND_HOST: 0.0.0.0
      SANIC_BIND_PORT: 8000
    volumes:
      - .:/app
    command:
      "sh -c 'poetry install && poetry run python -m unchanging_ink'"

  frontend:
    image: unchanging-ink-frontend:dev
    build:
      context: .
      target: frontend-base
      dockerfile: Dockerfile.dev
    read_only: false
    volumes:
      - ./web/unchanging-ink:/app
    command: "sh -c 'cd /app && npm install && npm run dev'"

