version: '3'

services:
  backend:
    image: unchanging-ink:dev
    build:
      context: .
      target: backend-builder
      dockerfile: Dockerfile
    read_only: false
    environment:
      SANIC_DEBUG: "true"
      SANIC_DB_HOST: db
      SANIC_DB_USER: sanic
      SANIC_DB_PASSWORD: toomanysecrets
      SANIC_DB_NAME: sanic
      SANIC_ACCESS_LOG: "true"
      SANIC_WORKERS: 1
      SANIC_BIND_HOST: 0.0.0.0
      SANIC_BIND_PORT: 8000
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      POETRY_CACHE_DIR: /cache
    volumes:
      - .:/app
      - backend_venv:/app/.venv
      - poetry_cache:/cache
    command:
      "sh -c 'poetry install && poetry run python -m unchanging_ink'"

  worker:
    image: unchanging-ink-worker:dev
    build:
      context: .
      target: worker-builder
      dockerfile: Dockerfile
    read_only: false
    environment:
      SANIC_DEBUG: "true"
      SANIC_DB_HOST: db
      SANIC_DB_USER: sanic
      SANIC_DB_PASSWORD: toomanysecrets
      SANIC_DB_NAME: sanic
      SANIC_ACCESS_LOG: "true"
      SANIC_WORKERS: 1
      SANIC_BIND_HOST: 0.0.0.0
      SANIC_BIND_PORT: 8000
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      POETRY_CACHE_DIR: /cache
    volumes:
      - .:/app
      - worker_venv:/app/.venv
      - poetry_cache:/cache
    command:
      "sh -c 'poetry install -E worker && poetry run python -m unchanging_ink.worker'"

  frontend:
    image: unchanging-ink-frontend:dev
    build:
      context: .
      target: frontend-base
      dockerfile: Dockerfile.dev
    read_only: false
    volumes:
      - ./web/unchanging-ink:/app
    command: "sh -c 'cd /app && npm install && npm run dev'"

volumes:
  backend_venv:
    driver_opts:
      type: tmpfs
      device: tmpfs
  worker_venv:
    driver_opts:
      type: tmpfs
      device: tmpfs
  poetry_cache:
