- name: Test compose
  hosts: all
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        dest: "unchanging-ink/"
        src: "../{{ item }}"
      with_items:
        - docker-compose.yml
        - Dockerfile
        - default.conf
    - name: Update pip and setuptools
      ansible.builtin.pip:
        state: latest
        name:
          - pip
          - setuptools
    - name: Install docker-compose
      ansible.builtin.pip:
        state: latest
        name:
          - docker-compose
    - name: Set environment
      ansible.builtin.copy:
        dest: "unchanging-ink/.env"
        content: |
          DEPLOY_VERSION={{ CI_COMMIT_REF_SLUG }}
          IMAGE_BASE={{ CI_REGISTRY_IMAGE }} 
          PROXYPORT=23230
          COMPOSE_PROJECT_NAME=unchanging-ink
    - name: Log in to private registry
      community.docker.docker_login:
        username: "{{ CI_REGISTRY_USER }}"
        password:  "{{ CI_REGISTRY_PASSWORD }}"
        registry_url: "{{ CI_REGISTRY }}"
    - name: Bring up
      community.docker.docker_compose:
        project_src: unchanging-ink
        project_name: unchanging-ink
        state: present
        pull: yes
        restarted: yes
        build: no
      environment:
        PATH: "/home/{{ ansible_user }}/.local/bin:{{ ansible_env.PATH }}"

