- name: Deploy selected version
  hosts: all
  tasks:
    - name: Update pip and setuptools
      ansible.builtin.pip:
        state: latest
        name:
          - pip
          - setuptools
    - name: Install docker-compose
      ansible.builtin.pip:
        state: latest
        name:
          - docker-compose
