- name: Copy files
  ansible.builtin.copy:
    dest: "unchanging-ink/"
    src: "{{ playbook_dir }}/../{{ item }}"
    with_items:
      - docker-compose.yml
      - Dockerfile
      - default.conf
- name: Set environment
  ansible.builtin.copy:
    dest: "unchanging-ink/.env"
    content: |
      DEPLOY_VERSION={{ CI_COMMIT_REF_SLUG }}
      IMAGE_BASE={{ CI_REGISTRY_IMAGE }} 
      PROXYPORT=23230
      COMPOSE_PROJECT_NAME=unchanging-ink
- name: Log in to private registry
  community.docker.docker_login:
    username: "{{ CI_REGISTRY_USER }}"
    password:  "{{ CI_REGISTRY_PASSWORD }}"
    registry_url: "{{ CI_REGISTRY }}"
- name: Bring up
  community.docker.docker_compose:
    project_src: unchanging-ink
    project_name: unchanging-ink
    state: present
    pull: yes
    restarted: yes
    build: no
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

