"""initial

Revision ID: 71308b14ac62
Revises: 
Create Date: 2021-04-18 13:45:12.880947

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "71308b14ac62"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interval",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ith", sa.LargeBinary(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node",
        sa.Column("start", sa.BigInteger(), nullable=False),
        sa.Column("end", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.LargeBinary(length=64), nullable=False),
        sa.PrimaryKeyConstraint("start", "end", name="node_pk"),
    )
    op.create_table(
        "signed_timestamp",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("kid", sa.String(length=128), nullable=False),
        sa.Column("timestamp", sa.String(length=32), nullable=False),
        sa.Column("signature", sa.LargeBinary(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timestamp_proof",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("interval", sa.BigInteger(), nullable=False),
        sa.Column("proof", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["signed_timestamp.id"], deferrable=True),
        sa.ForeignKeyConstraint(["interval"], ["interval.id"], deferrable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timestamp_proof")
    op.drop_table("signed_timestamp")
    op.drop_table("node")
    op.drop_table("interval")
    # ### end Alembic commands ###
