"""initial

Revision ID: d470dc1bd829
Revises: 
Create Date: 2021-04-17 18:41:42.765977

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "d470dc1bd829"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interval",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ith", sa.LargeBinary(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node",
        sa.Column("start", sa.BigInteger(), nullable=False),
        sa.Column("end", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.LargeBinary(length=64), nullable=False),
        sa.PrimaryKeyConstraint("start", "end", name="node_pk"),
    )
    op.create_table(
        "signed_timestamp",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("kid", sa.String(length=128), nullable=False),
        sa.Column("timestamp", sa.String(length=32), nullable=False),
        sa.Column("signature", sa.LargeBinary(length=64), nullable=False),
        sa.Column("interval", sa.BigInteger(), nullable=True),
        sa.Column("proof", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interval"],
            ["interval.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signed_timestamp")
    op.drop_table("node")
    op.drop_table("interval")
    # ### end Alembic commands ###
